import Head from 'next/head'
import Image from 'next/image'
import classes from '../styles/Home.module.scss'
import transparent_image from '../Assets/Fleece/Fleece transparent.png'

export default function Home() {
  return (
    <div className={classes.container}>
      <Head>
        <title>Zombie Killer Death Trap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Image src={transparent_image} /> */}
      <div className={classes.banner}>

        <div className={classes.content}>

        </div>


        <div className={classes.image}>

          <img src='https://i.imgur.com/B5EM5a9.png' />
        </div>
      </div>
    </div>
  )
}
